### ISSUE TITLE
An error occurred when I ran “KrigR” for downscaling. Because this package is used for the first time, I hope to get your help!

### ISSUE THREAD

**Issue by loupeiqing** [ErikKusch/KrigR#3]
Dear Erik:
An error occurred when I ran “KrigR” for downscaling. Because this package is used for the first time, I hope to get your help!

code:
library(KrigR)
library(tidyr)
library(ggplot2)
library(viridis)
library(cowplot)
library(rosm)
library(gismms)
## THREE-STEP PROCESS (By Itself)
# Downloading ERA5-Land air temperature reanalysis data in 12-hour intervals for 02/01/1995 - 04/01/1995 (DD/MM/YYYY). API User and Key in this example are non-functional. Substitute with your user number and key to run this example.
Extent <- extent(c(75,115,30,45)) # roughly the extent of Mongolia

API_User <- "****"
API_Key <- "****"
State_Raw <- download_ERA(
Variable = "2m_temperature",
DataSet = "era5-land",
DateStart = "1984-01-01",
DateStop = "1984-12-31",
TResolution = "month",
TStep = 12,
Extent = Extent,
API_User = API_User,
API_Key = API_Key
)
State_Raw # a raster brick with 6 layers at resolution of ~0.1Â°

# Downloading GMTED2010-data at resolution and extent obtained by a call to download_ERA and a target resolution of .02.
Covs_ls <- download_DEM(
Train_ras = State_Raw,
Target_res = .02,
Keep_Temporary = TRUE
)

Covs_ls # a list with two elements: (1) GMTED 2010 data at training resolution, and (2) GMTED 2010 data aggregated as close as possible to a resolution of 0.02
# Kriging the data sets prepared with the previous functions.
krigStart <- Sys.time()
State_Krig <- krigR(
Data = State_Raw, # data we want to krig as a raster object
Covariates_coarse = Covs_ls[[1]], # training covariate as a raster object
Covariates_fine = Covs_ls[[2]], # target covariate as a raster object
Keep_Temporary = FALSE,
Cores = 1,
FileName = "downscaledERA-5.nc",
Dir = "F://Downscaling_try"
)
KrigStop <- Sys.time()

Error：
> # Kriging the data sets prepared with the previous functions.
> krigStart <- Sys.time()
> State_Krig <- krigR(
+ Data = State_Raw, # data we want to krig as a raster object
+ Covariates_coarse = Covs_ls[[1]], # training covariate as a raster object
+ Covariates_fine = Covs_ls[[2]], # target covariate as a raster object
+ Keep_Temporary = FALSE,
+ Cores = 1,
+ FileName = "downscaledERA-5.nc",
+ Dir = "F://Downscaling_try"
+ )
| | 0%[1] "Kriging failed for layer 1. Error message produced by autoKrige function: Error in predict.gstat(g, newdata = newdata, block = block, nsim = nsim, : \n out of dynamic memory (try local kriging?)\n"
Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘rasterize’ for signature ‘"NULL", "RasterLayer"’

**Comment by ErikKusch** [comment]
Hi there,

I strongly suspect that this error is caused by your PC not having enough RAM to carry out kriging over the entire study area using the default of `nmax = Inf` in `krigR()`. I get this from this part of the error message:

`out of dynamic memory (try local kriging`

By default, `krigR()` uses `nmax = Inf` to krig using the domain-average relationship. You may get around this issue by setting `nmax` to any number and forcing local kriging. Personally, I usually use around 80 when doing local kriging of ERA5-Land air temperature.

I am currently running your code on my end to make sure I can execute it properly and will update this issue when I have either managed to run it without any issue or have reproduced your issue.

Please let me know if switching to local kriging solves your issue in the meantime.

**Comment by ErikKusch** [comment]
Your code compiled on my machine without a hitch. It took some time and I do recommend tuning the `nmax` argument to a distance that sensible represents the climate regimes in your study area, given your study variable, and training resolution. For Era5-Land and air temperature, you can usually coast by with any `nmax` between 80 and 480. Setting an `nmax` reduces RAM usage as well as processing time.
