### ISSUE TITLE
Issues when use more than 5 cores.

### ISSUE THREAD

**Issue by Doltrix** [ErikKusch/KrigR#38]
Hello. I'm here again :)
I have discovered that when using the parameter Cores in more than 5, there are problems of instability in the system and my pc crashes (at least in my case). This did not happen to me a few months ago, when I even used detectCores(). My pc has 20 cores but now I can only use up to 5 or my system crashes.

Thanks for your help.

**Comment by ErikKusch** [comment]
I am afraid I have not experienced such behaviour before. Without a minimal working example, I don't know how to begin addressing this. I have changed nothing about the parallelisation in the last few months, so I am wonder if this might be caused by changes to your system rather than `KrigR`.

If you have any ideas how to begin investigating this, please let me know. I ran your earlier code (#36) with all cores available on my machine and encountered no issues.

**Comment by Doltrix** [comment]
Then it must be a problem in my system. Thanks for telling me about it.
One more question, now I experienced this error:

download_ERA() is starting. Depending on your specifications, this can take a significant time.
User 188389 for cds service added successfully in keychain
Staging 252 download(s).
  |                                                                          |   0%Error in `when()`:
! At least one matching condition is needed.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `when()`:
! At least one matching condition is needed.
---
Backtrace:
    ▆
 1. └─KrigR::download_ERA(...)
 2.   ├─... %dopar% ...
 3.   │ └─e$fun(obj, substitute(ex), parent.frame(), e$data)
 4.   ├─... %:% ...
 5.   └─purrr::when(!file.exists(file.path(Dir, FileNames_vec[Downloads_Iter])))
Run rlang::last_trace(drop = FALSE) to see 2 hidden frames.


I employed the same code I provided you with

**Comment by ErikKusch** [comment]
As per #34, you will need to unload `tidyverse` libraries. Avoiding this error is part of my development goals listed in #25.
