### ISSUE TITLE
Parsing Issue in krigR function

### ISSUE THREAD

**Issue by rafalopespx** [ErikKusch/KrigR#4]
Hi there, amazing package Erik!

So, I am using KrigR to do some kriging with data points, I noted an issue in the use as a pipeline of `krigR` function.

I think the issue is the following:
When I pass to the function the name of ID column it is not able to match it with the one that I specified.  
When renaming the column as "ID" the pipeline works pretty well, so I think it is a issue with parsing the name inside the `krigR` function.

Here I give you a working example with the Bigfoot data from the [tutorial](https://www.erikkusch.com/talks/krigr---climate-data-for-your-spatial-analyses_html#kriging-for-point-data) kriging around data points.

```
doesnt_work<-krigR(Variable = '2m_temperature',
      DataSet = 'era5-land',
      Type = "reanalysis", 
      DateStart = '2012-12-29',
      DateStop = '2012-12-31',
      TResolution = 'day',
      TStep = 1,
      Extent = Bigfoot_df, # the point data with Lon and Lat columns
      Buffer = 0.1, # a 0.1 degree buffer should be drawn around each point
      ID = "FID_", # this is the column which holds point IDs
      API_User = API_User,
      API_Key = API_Key,
      Target_res = .02,
      Cores = 1,
      maxdist = 0.1,
      FileName = "Points.nc",
      Keep_Temporary = FALSE)  
```
It returns the following error:

```[1] "Aggregating to temporal resolution of choice"
Error in `[.data.frame`(Points, , ID) : undefined columns selected
```

My solution was the following:
```
Bigfoot_sample <- sample(x = 1:dim(Bigfoot.data)[1], size = 60)
Bigfoot_df <- Bigfoot.data[Bigfoot_sample, ]
Bigfoot_df<- Bigfoot_df %>% 
  select(FID_, Lat, Lon) %>% 
  setNames(c("ID", "Lat", "Lon"))

do_work<-krigR(Variable = '2m_temperature',
               DataSet = 'era5-land',
               Type = "reanalysis", 
               DateStart = '2012-12-29',
               DateStop = '2012-12-31',
               TResolution = 'day',
               TStep = 1,
               Extent = Bigfoot_df, # the point data with Lon and Lat columns
               Buffer = 0.1, # a 0.1 degree buffer should be drawn around each point
               ID = "ID", # this is the column which holds point IDs
               API_User = API_User,
               API_Key = API_Key,
               Target_res = .02,
               Cores = 1,
               maxdist = 0.1,
               FileName = "Points.nc",
               Keep_Temporary = FALSE)
```
Which works fine!

Probably, this can be solved with a clever parsing inside all the functions, a good way to pick column names is using `{{column_name}}` inside the function. 

As I investigated the problem seems to be inside the `krigR` function or/and inside the `download_DEM` function.
I think maybe it is on the scope of the function `buffer_points` which is unfortunately not exported with the namespace `KrigR`, but called. I don't know if this function is a exported function from a dependency package.

I Think if resolving this you can too improve the `krigR` function, with parsing the column names in the same way when parsing the "ID" column name.

**Comment by ErikKusch** [comment]
Hi Rafa,

thanks a bunch for the super detailed issue. I have not been able to reconstruct your issue 100% (maybe you are on an older version on `KrigR`), but I did find an issue with parsing of the ID into the lower levels of the pipeline function. I fixed this with this [commit](https://github.com/ErikKusch/KrigR/commit/6a639c74d6a7c8b9b3aa6b79d2cedda8b8eec707) and the code you shared above works on my end.

Please note that all future workshop material for the package lives [here](https://www.erikkusch.com/post/krigr-mats/krigrworkshop/) and I have removed the material you were looking at since it was outdated (luckily not in the sections of importance to you). Terribly sorry about those duplicates.

Please let me know if reinstalling `KrigR` did not solve the issue for you.

Cheers,
Erik
