### ISSUE TITLE
Error: [time<-] length(value) != nlyr(x) when TResolution = "hour"

### ISSUE THREAD

**Issue by Doltrix** [ErikKusch/KrigR#44]
Hello, I received this error during a download.
Why does it happen?

Precip_00_20_hour<-download_ERA(
  Variable = 'total_precipitation',
  Type = "reanalysis",
  DataSet = "era5-land",
  DateStart = "2000-01-01",
  DateStop = "2020-12-31",
  TResolution = "hour",
  TStep = 1,
  Extent = extent(-78.83, -77.87, -0.73, 0.34),
  Buffer = 0.5,
  Dir = ('E:/'),
  FileName = 'Precip_00_20_hour',
  API_Key = 'API_Key',
  API_Key = 'API_Key',
  TryDown = 10,
  verbose = TRUE,
  Cores =5,
  TimeOut = 36000)

Checking for known data issues.
Loading downloaded data for masking and aggregation.
Aggregating to temporal resolution of choice
**Error: [time<-] length(value) != nlyr(x)**

**Comment by ErikKusch** [comment]
First of all, thanks for pointing these bugs out to me as you hit them! This is really valuable for me. :-) 

Fixed with #45. Please re-install `KrigR`.

This was an oversight that had to do with how time sequences were assigned for hour-level records. This issue was introduced with #39. This only affects downloads at `TResolution = "hour"` and did not impact any download values in otherly specified outputs.
