### ISSUE TITLE
Error when downloading ERA5 Data: Error: [varnames<-,SpatRaster]

### ISSUE THREAD

**Issue by gsaabogado** [ErikKusch/KrigR#52]
Hi Erik, I have an error when using the download_ERA function.

Here is my code: 

#### Get the boundaries of mexico ####
mexico <- giscoR::gisco_get_countries(country = "MX", resolution = 10)

#### Extract mean temperature ####
mx_tmp = download_ERA(
  variable = "2m_temperature", 
  DataSet = "era5-land",
  DateStart = "1998-01-01", 
  DateStop = "1999-02-01", 
  TResolution = "month",
  TStep = 1,
  Dir = "01_data/08_copernicus/2m_tmp",
  FileName = "mexico_2m_tmp", 
  Extent = extent(14.45, 32.76,-117.13,-86.72),
  API_User = "***",
  API_Key = "*******************"
)

The error is: 

Masking according to shape/buffer polygon
Aggregating to temporal resolution of choice
Error: [varnames<-,SpatRaster] cannot set these names

Do you know how to correct it?

Best

**Comment by ErikKusch** [comment]
Hi Luis,

easy fix. Make your `variable` argument into a capitalised version: `Variable`. This is how `KrigR` requires variable naming and that is why name assignment fails later in the script. The reason you can download data is because the underlying `ecmwfr` is not case-sensitive.

Thus, you code should read
```r
mx_tmp = download_ERA(
Variable = "2m_temperature",
DataSet = "era5-land",
DateStart = "1998-01-01",
DateStop = "1999-02-01",
TResolution = "month",
TStep = 1,
Dir = "01_data/08_copernicus/2m_tmp",
FileName = "mexico_2m_tmp",
Extent = extent(14.45, 32.76,-117.13,-86.72),
API_User = "",
API_Key = "****************"
)
```

Cheers
