### ISSUE TITLE
Fix loading dependencies

### ISSUE THREAD

**Issue by DavidS45000** [ErikKusch/KrigR#59]
Hello,

Thank you very much for the package you created!

But I have a question, is it possible to fix the dependencies of your package to avoid loading all the libraries in the R environment?

Example :
Instead of writing **library(ecmwfr)** write rather at the level of the function used **ecmwfr::wf_set_key**

This methodology allows you to use the functions of your package without loading other dependencies (with libraries()) in the R environment and to avoid having:
- **package conflicts**
- **errors like**:
Error in wf_set_key(user = as.character(API_User), key = as.character(API_Key), :
   could not find function "wf_set_key"

Thank you  and have a good day !

David

**Comment by ErikKusch** [comment]
Hi David,

could I ask you to provide me with an example of where this behaviour is causing you issues? I ask to figure out how pressing this issues is.

Currently, `KrigR` just loads all dependencies as you already figured. I have since found a better way of doing this in package development via importing a specific function from a specific package. This is done differently to what you propose. That is to my knowledge, please let me know if you are aware of something I am not. :-) 

I plan to wholly re-deploy this package next year with several development [milestones](https://github.com/ErikKusch/KrigR/milestones). This will include restructuring dependencies and I will make sure to rectify the dependency load issue you raised here. I track this in #25. I am therefore closing this issue.

Cheers,
Erik
