### ISSUE TITLE
error in wf_set_key

### ISSUE THREAD

**Issue by YQ303** [ErikKusch/KrigR#80]
Hi,

    I'm using the "download_ERA" function and I keep encountering the following  error:
   “error in wf_set_key(user = as.character(API_User), key = as.character(API_Key),： 
   unused argument (service = API_Service)”
   I checked the wf_set_key function in ecmwfr package (https://rdrr.io/cran/ecmwfr/man/wf_set_key.html) and it seems that there is no argument name "service" in  wf_set_key function now. I guess this may cause above error. If so, I wonder if there is any possible solution for this (I'm using KrigR_0.1.3  and ecmwfr_2.0.2).

 Thanks for any suggestions!!!

**Comment by ErikKusch** [comment]
Hi @YQ303 !

Thanks for including the package versions in your issue! To resolve this, please install the development version of `KrigR` like so:

```r
devtools::install_github("https://github.com/ErikKusch/KrigR", ref = "Development")
```

That way, you will get to use `KrigR` version 0.4.0 - the latest one as of me writing this comment. With this version, I address the switch from the old Climate Data Store to a new one with slightly different API specifications. The main branch of `KrigR` will soon be updated to what is currently on the development branch.

With this new version, you have to use the `CDownloadS()` function instead of the deprecated `download_ERA()` function. I detail how to set up with the new CDS [here](https://www.erikkusch.com/courses/krigr/setup/) and demonstrate how to use the new and improved functions [here](https://www.erikkusch.com/courses/krigr/quickstart/).
